Avoid handling flow erros in hosted page
descope/auth-hosting pull request #141
Opened 2023-10-31 08:05 UTC by talaharoni

## Related Issues

Related to https://github.com/descope/etc/issues/4478

## Description

When the flow gets an error in the hosted page, the error should be returned and not show the welcome page

## Must

- [ ] 📱 Responsiveness (mobile/XL resolutions)
- [ ] 🧪 Tests
- [ ] 📃 Documentation (if applicable)

2023-10-31 12:40 UTC, omercnet approved these changes

2023-10-31 12:41 UTC, omercnet requested changes
Add tests to catch both cases ? To avoid regression

2023-10-31 13:05 UTC, talaharoni commented
> Add tests to catch both cases ? To avoid regression

There is already test for the missing projectId.
As there is no handling for errors I don't think it's relevant to check "something doesn't happen"

2023-11-01 19:27 UTC, omercnet approved these changes

2023-11-01 19:31 UTC, merged